language: cpp
os:
  - linux
  - osx
# the default precise linux container has gcc 4.6
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - tcsh
script: |
  set -e
  if [[ $BATCH == true ]]; then
    echo -e "*** testing batch mode in Python version $PYVER ***\n"
    bash -x ./scripts/newinstall.sh -cb -${PYVER}
  else
    echo -e "*** testing interactive mode in Python version $PYVER ***\n"
    echo -e "yes\nyes" | bash -x ./scripts/newinstall.sh -c -${PYVER}
  fi
  echo -e "*** Testing initializaion of shell environment ***\n"
  case $MANGLER in
    tcsh)
      # csh_20110502-2ubuntu2_amd64.deb from ubuntu:trusty (travis) opens a new
      # shell interactive shell when passed--version
      tcsh --version
      tcsh -ec 'source loadLSST.csh && echo $EUPS_PKGROOT'
      ;;
    *)
      bash --version
      bash -ec 'source loadLSST.bash && echo $EUPS_PKGROOT'
      ;;
  esac
env:
  - BATCH=true PYVER="2"
  - BATCH=true PYVER="3"
  - BATCH=false PYVER="2"
  - BATCH=false PYVER="3"
  - MANGLER=tcsh BATCH=true PYVER="3"
matrix:
  # osx builds are often very slow to start due to high demand
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - os: linux
      env:
      compiler:
      language: ruby
      rvm: '2.4'
      script: bundle exec rspec --format doc
notifications:
  email: false
  hipchat:
    rooms:
      secure: vdljuR+bCqCLkYekrsOHsbYb0sXXodGXc9q5GQA3cOxd/TP/vztBCcPatTSFZpHsYAMnfXqul98X1W5/vQ+eqKtCCFMF7+GKrS179cIYdrohMhU/1Ltbvx2hTofjuYi/T/8jF8APswxE2hBu0RJYLO+btPFMz0qhLA8owpmY4FY=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
