---
sudo: false
language: c
matrix:
  include:
    - &accept
      os: linux
      env: BATCH=false
      services:
        - docker
      script: ./tests/docker-acceptance.sh

    - <<: *accept
      env: BATCH=true

    - <<: *accept
      env: BATCH=true ANCIENT_BASH="3.2.57"

    - <<: *accept
      env: BATCH=false ANCIENT_BASH="3.2.57"

    - <<: *accept
      env: MANGLER=tcsh BATCH=true

    - &ruby
      env: TEST=rubocop
      language: ruby
      rvm: '2.5'
      script: bundle exec rubocop

    - <<: *ruby
      env: TEST=rspec-bash
      script: bundle exec rspec --format doc

    - &plumb
      env: TEST=markdownlint
      language: c
      services:
        - docker
      script: ./tests/mdl.sh

    - <<: *plumb
      env: TEST=yamllint
      script: ./tests/yamllint.sh

    - <<: *plumb
      env: TEST=shellcheck
      script: ./tests/shellcheck.sh

    - <<: *plumb
      env: TEST=hadolint
      script: ./tests/hadolint.sh

    - env: TEST=make
      script: ./tests/make.sh
  # osx builds are often very slow to start due to high demand
  fast_finish: true
  # allow_failures:
  #  - os: osx
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+(\.\d+)?$/
notifications:
  email: false
